use_frameworks!

target 'FunBox_Example' do
  platform :ios, '11.0'
  pod 'FunBox', :path => '../'
#  pod 'FunCoreKit', :path => '../'
  pod 'FunAlamofire/HandyJSON', :path => '../'
  pod 'FunModules', :path => '../'
  pod 'RAMAnimatedTabBarController'
  pod 'RichTextView'
  
  # CoreKit
#  pod 'FunBox'
#  pod 'FunAlamofire'
#  pod 'FunModules'
  pod 'HandyJSON'
  pod 'Hue'
  pod 'KingfisherWebP'
#  pod 'Moya', '~> 14.0.0'
  pod 'RxAlamofire'
  pod 'libwebp'
  pod 'MJRefresh'
  pod 'RxRelay'
  pod 'Moya/RxSwift', '~> 14.0.0'
  
#  pod 'Toast-swift'

  target 'FunBox_Tests' do
    inhibit_all_warnings!
    inherit! :search_paths

#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
