use_frameworks!

target 'FunBox_Example' do
  platform :ios, '10.0'
  pod 'FunBox', :path => '../'
#  pod 'Toast-swift'

  target 'FunBox_Tests' do
    inhibit_all_warnings!
    inherit! :search_paths

#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
